// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_Token                           13
#define gattdb_PID                             16
#define gattdb_Version                         18
#define gattdb_Authentication                  20
#define gattdb_DeviceID                        23
#define gattdb_BeaconKey                       25
#define gattdb_WifiCfg                         27

typedef enum
{
    mesh_provisioning_service      = 0x0001,
    mesh_proxy_service             = 0x0002,
    mi_service_cap                 = 0x0004,
    bg_gattdb_data_all_caps = 0x0007
} bg_gattdb_data_cap_t;

#endif
