#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = iar.targets.arm.M3{1,0,8.32,1
#
app_ble.xrm3: package/cfg/app_ble.xrm3.mak

clean::
	-$(RM) package/cfg/app_ble.xrm3.mak
